---
- name: Stopping Deluge docker container
  community.docker.docker_compose:
    project_src: "{{ deluge_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ deluge_home_dir }}"
    - "{{ deluge_config_dir }}"
