---
- name: Stopping Watcharr docker container
  community.docker.docker_compose:
    project_src: "{{ watcharr_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ watcharr_home_dir }}"
    - "{{ watcharr_config_dir }}"
