homer_deployment: install

homer_home_dir: "{{ home_dir }}/homer/"

# Homer configuration vars
#########################
homer_image: 'b4bz/homer'
homer_container_name: 'homer'
homer_config_dir: '/etc/homer/assets'
homer_port: 8080
