---
- name: Create application user
  ansible.builtin.user:
    name: node_exporter
    create_home: false
    shell: /sbin/nologin
  register: created_node_exporter_user

- name: Display created users
  ansible.builtin.debug:
    msg: "User: uid:{{ created_node_exporter_user.uid }} name:{{ created_node_exporter_user.name }} group:{{ created_node_exporter_user.group }}"

- name: Docker pull node_exporter image
  community.docker.docker_image:
    name: "{{ node_exporter_docker_image }}"
    source: pull

- name: Create systemd service
  ansible.builtin.template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: node_exporter
    group: node_exporter
    mode: "0644"
  notify: Restart node-exporter service

- name: Start and enable service
  ansible.builtin.systemd:
    name: node-exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers

- name: Wait for service to become available
  ansible.builtin.uri:
    url: "http://localhost:{{ node_exporter_port }}/"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
