---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "755"
  with_items:
    - "{{ node_exporter_home_dir }}"

- name: Copy Node Exporter docker compose file
  ansible.builtin.template:
    force: true
    src: "docker-compose.yaml.j2"
    dest: "{{ node_exporter_home_dir }}/docker-compose.yaml"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "644"

- name: Start container using docker compose
  community.docker.docker_compose:
    project_src: "{{ node_exporter_home_dir }}"
    files:
    - docker-compose.yaml
  register: output

- name: Output log of docker
  ansible.builtin.debug:
    var: output

- name: Wait for Node Exporter service to become available
  ansible.builtin.uri:
    url: "http://localhost:{{ node_exporter_port }}/"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
