---
- name: Install Node exporter docker container
  ansible.builtin.include_tasks:
    file: roles/docker_node_exporter/tasks/install.yml
  when: node_exporter_deployment == 'install'

- name: Remove Node exporter docker container
  ansible.builtin.include_tasks:
    file: roles/docker_node_exporter/tasks/removal.yml
  when: node_exporter_deployment == 'removal'
