---
- name: Stopping Node exporter docker container
  community.docker.docker_compose:
    project_src: "{{ node_exporter_home_dir }}"
    state: absent

- name: Remove directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ node_exporter_home_dir }}"
