---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "755"
  with_items:
    - "{{ homebox_home_dir }}"
    - "{{ homebox_config_dir }}"

- name: Copy Homebox docker compose file
  ansible.builtin.template:
    force: true
    src: "docker-compose.yaml.j2"
    dest: "{{ homebox_home_dir }}/docker-compose.yaml"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "644"

- name: Copy Homebox database files
  ansible.builtin.copy:
    src: "roles/docker_homebox/files/"
    dest: "{{ homebox_config_dir }}/"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0644'

- name: Start container using docker compose
  community.docker.docker_compose:
    project_src: "{{ homebox_home_dir }}"
    files:
    - docker-compose.yaml
  register: output

- name: Output log of docker
  ansible.builtin.debug:
    var: output
