---
- name: Stopping Homebox docker container
  community.docker.docker_compose:
    project_src: "{{ homebox_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ homebox_home_dir }}"
    - "{{ homebox_config_dir }}"
