---
- name: Stopping Speed Test docker container
  community.docker.docker_compose:
    project_src: "{{ speed_test_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ speed_test_home_dir }}"
    - "{{ speed_test_config_dir }}"
