---
- name: Stop and disable Node exporter service
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true

- name: Stop Node exporter container
  community.docker.docker_container:
    name: "{{ node_exporter_service_name }}"
    state: stopped

- name: Remove Node exporter container
  community.docker.docker_container:
    name: "{{ node_exporter_service_name }}"
    state: absent

- name: Recursively remove directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/{{ node_exporter_service_name }}.service"

- name: Remove node_exporter user
  ansible.builtin.user:
    name: node_exporter
    state: absent
    remove: true
