---
- name: Stopping Radarr docker container
  community.docker.docker_compose:
    project_src: "{{ radarr_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ radarr_home_dir }}"
    - "{{ radarr_config_dir }}"
