---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "755"
  with_items:
    - "{{ portainer_agent_home_dir }}"

- name: Copy Portainer Agent docker compose file
  ansible.builtin.template:
    force: true
    src: "docker-compose.yaml.j2"
    dest: "{{ portainer_agent_home_dir }}/docker-compose.yaml"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "644"

- name: Start container using docker compose
  community.docker.docker_compose:
    project_src: "{{ portainer_agent_home_dir }}"
    files:
    - docker-compose.yaml
  register: output

- name: Output log of docker
  ansible.builtin.debug:
    var: output
