---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "755"
  with_items:
    - "{{ kuma_home_dir }}"
    - "{{ kuma_config_dir }}"

- name: Copy Kuma docker compose file
  ansible.builtin.template:
    force: true
    src: "docker-compose.yaml.j2"
    dest: "{{ kuma_home_dir }}/docker-compose.yaml"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "644"

- name: Copy Kuma config file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kuma_config_dir }}/"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0644'
  with_fileglob:
    - roles/docker_kuma/files/kuma.db

- name: Start container using docker compose
  community.docker.docker_compose:
    project_src: "{{ kuma_home_dir }}"
    files:
    - docker-compose.yaml
  register: output

- name: Output log of docker
  ansible.builtin.debug:
    var: output
