---
- name: Stopping Kuma docker container
  community.docker.docker_compose:
    project_src: "{{ kuma_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kuma_home_dir }}"
    - "{{ kuma_config_dir }}"
