grafana_deployment: install

grafana_home_dir: /home/horia/grafana

# https://docs.linuxserver.io/general/understanding-puid-and-pgid
puid: 1000
pgid: 1000
timezone: 'Europe/London'

home_dir: /home/horia

# grafana configuration vars
###########################
grafana_image: 'grafana/grafana-oss:latest'
grafana_config_dir: /etc/grafana
grafana_data_dir: /var/lib/grafana
grafana_host: 192.168.5.11
grafana_port: 3000

# https://grafana.com/docs/grafana/latest/administration/configuration/
root_url: "http://{{ grafana_host }}:{{ grafana_port }}"
grafana_admin_user: admin
grafana_admin_password: admin
# The admin password will be saved in a encrypted vault file for each environment
level: INFO

# https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
grafana_env_vars: {}

# https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
grafana_dashboards:
  apiVersion: 1
  providers:
    - name: dashboards
      type: file
      updateIntervalSeconds: 30
      options:
        path: "{{ grafana_config_dir }}/dashboards"
        foldersFromFilesStructure: true
