---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: horia
    group: horia
    mode: "755"
  with_items:
    - "{{ sonarr_home_dir }}"
    - "{{ sonarr_config_dir }}"

- name: Copy Sonarr docker compose file
  ansible.builtin.template:
    force: true
    src: "docker-compose.yaml.j2"
    dest: "{{ sonarr_home_dir }}/docker-compose.yaml"
    owner: horia
    group: horia
    mode: "644"

- name: Copy Sonarr database file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ sonarr_config_dir }}/"
    owner: horia
    group: horia
    mode: '0644'
  with_items:
    - "roles/docker_sonarr/files/sonarr.db"

- name: Start Sonarr container using docker compose file
  community.docker.docker_compose:
    project_src: "{{ sonarr_home_dir }}"
  register: output

- name: Output log of docker
  ansible.builtin.debug:
    var: output
