n8n_deployment: install

# n8n configuration vars
###########################
n8n_image: 'docker.n8n.io/n8nio/n8n:latest'
n8n_home_dir: '{{ home_dir }}/n8n'
n8n_internal_data_dir: /etc/n8n  # n8n internal data directory on the host
n8n_local_files: '{{ n8n_home_dir }}/local-files'  # file I/O from workflows on the host
n8n_port: 5678
