portainer_deployment: install

portainer_home_dir: "{{ home_dir }}/portainer"

# Portainer configuration vars
###########################
portainer_image: 'portainer/portainer-ce:latest'
portainer_config_dir: /etc/portainer
portainer_port: 9443
