# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
# - name: Install Docker
#     ansible.builtin.shell: curl -sSL https://get.docker.com | sh

---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_only: true
  tags:
    - packages

- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true
  tags:
    - docker

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true
  tags:
    - docker

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - docker

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true
  tags:
    - docker

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  tags:
    - docker

- name: Ensure services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - docker
  tags:
    - docker

- name: Add the user to group "docker" user {{ user }}
  ansible.builtin.user:
    name: "{{ user }}"
    group: docker
  tags:
    - docker
