---

- name: Install Prometheus
  ansible.builtin.include_tasks:
    file: roles/docker_prometheus/tasks/install.yml
  when: prometheus_deployment == 'install'

- name: Remove Prometheus
  ansible.builtin.include_tasks:
    file: roles/docker_prometheus/tasks/remove.yml
  when: prometheus_deployment == 'remove'
