---
- name: Stopping docker Homer container
  community.docker.docker_compose:
    project_src: "{{ homer_home_dir }}"
    state: absent

- name: Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ homer_home_dir }}"
    - "{{ homer_config_dir }}"
